server:
  port: 9102
spring:
  application:
    name: world-service
  message: I am World Service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 15s
