server:
  port: 9101
spring:
  application:
    name: hello-service
  message: I am Hello Service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        healthCheckInterval: 15s
